language: node_js
node_js:
  - "5"

env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - npm install -g bower protractor

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - gulp connect &
  - webdriver-manager start &
  - npm run protractor
